language: minimal

addons:
  apt:
    packages:
      - python-pygments

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.1/hugo_0.58.1_Linux-64bit.deb -O /tmp/hugo.dpkg && sudo dpkg -i /tmp/hugo.dpkg

script:
  - hugo -v --cleanDestinationDir --baseURL="https://reaktor23.org"

deploy:
  provider: pages
  fqdn: reaktor23.org
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
