addons:
  apt:
    packages:
      - hugo
      - python-pygments

install:
  - rm -rf public || exit 0

script:
  - hugo -v -b https://reaktor23.org --cleanDestinationDir
  - echo 'reaktor23.org' > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
