---
languageCode: de-de
title: Reaktor23 - Hackerspace
theme: reaktor23
baseurl: ""
enableEmoji: true

menu:
  main:
    - name: Blog
      url: /
      weight: -1
    - name: About
      url: /about/
    - name: Projects
      url: /projects/
    - name: Talks
      url: /talks/
  foot:
    - name: Impressum / Datenschutz
      url: /impressum/
  rss:
    - name: Blog
      url: /blog/index.xml
    - name: Projects
      url: /projects/index.xml
    - name: All
      url: /index.xml

imaging:
  resampleFilter: Lanczos
  quality: 80

markup:
  goldmark:
    renderer:
      unsafe: true
