---
languageCode: de-de
title: Reaktor23 - Hackerspace
theme: reaktor23
baseurl: ""


menu:
  main:
    - name: Blog
      url: /
      weight: -1
    - name: About
      url: /about/
    - name: Projects
      url: /projects/
    - name: Talks
      url: /talks/
  foot:
    - name: Impressum / Datenschutz
      url: /impressum/

imaging:
  resampleFilter: Lanczos
  quality: 80
