baseURL = "http://reaktor23.org/"
languageCode = "en-us"
title = "Reaktor23 - Hackerspace"
theme = "reaktor23"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = -1
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Talks"
    url = "/talks/"

[[menu.foot]]
    name = "Impressum / Datenschutz"
    url = "/impressum/"

[imaging]
resampleFilter = "Lanczos"
quality = 80
