name: Deploy website

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install hugo 📦
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_0.87.0_Linux-64bit.deb -O /tmp/hugo.dpkg
          sudo dpkg -i /tmp/hugo.dpkg

      - name: Build website 🔧
        run: |
          hugo -v --cleanDestinationDir --baseURL="https://reaktor23.org"

      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
